// Product navigation, not a claim that sample dashboard evidence is live.
function managedProductIntro(plans) {
  const selected = plans.filter(plan => ["psa-workspace", "managed-visibility"].includes(plan.id));
  const money = atomic => Number(atomic) / 1e6;
  return `<style>
.mag-product{max-width:1180px;margin:auto;padding:32px 28px 42px}.mag-product a{color:#11d8ed}.mag-product nav{display:flex;gap:24px;align-items:center;flex-wrap:wrap}.mag-product .brand{display:flex;gap:10px;align-items:center;margin-right:auto;color:#eaf7ff;text-decoration:none;font-weight:800}.mag-product .brand img{width:46px;height:46px;object-fit:contain}.mag-product h1{font-size:clamp(2.3rem,5vw,4.1rem);line-height:1.08;letter-spacing:-.035em;max-width:800px;margin:36px 0 20px}.mag-product .lede{font-size:1.15rem;color:#aec6d8;max-width:780px}.mag-product .actions{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}.mag-product .cta{display:inline-block;padding:13px 19px;border:1px solid #11d8ed;border-radius:10px;text-decoration:none;font-weight:750}.mag-product .primary{background:#11d8ed;color:#041326}.mag-product .tiles{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin-top:24px}.mag-product article{padding:22px;background:#0a2744;border:1px solid #1e5774;border-radius:14px}.mag-product h2{margin:36px 0 8px;font-size:1.7rem}.mag-product h3{margin:0 0 10px;font-size:1.1rem}.mag-product .status{font-size:.75rem;text-transform:uppercase;letter-spacing:.08em;color:#f6c653}.mag-product .scope{font-size:.87rem;color:#9eb6c9}.mag-product .plan-price{font-size:1.75rem;font-weight:800;color:#f6c653}.mag-product .plans{grid-template-columns:repeat(2,minmax(0,1fr))}.mag-product details{padding:18px 0;border-bottom:1px solid #1e5774}.mag-product summary{cursor:pointer;font-weight:700}@media(max-width:700px){.mag-product{padding:22px 18px}.mag-product .tiles,.mag-product .plans{grid-template-columns:1fr}}
</style><section class="mag-product" aria-labelledby="managed-product-title">
<nav aria-label="MAG managed operations"><a class="brand" href="/"><img src="/mag-app-icon.png" alt="">MAG Managed Operations</a><a href="#demo">View demo</a><a href="#integrations">Integrations</a><a href="/ops/console">Tenant sign in</a></nav>
<p class="eyebrow" style="margin-top:40px">YOUR ORGANIZATION · YOUR BRAND · YOUR WORKSPACE</p>
<h1 id="managed-product-title">One workspace for the fleet.<br>A service desk for the team.</h1>
<p class="lede">Bring endpoint evidence, tickets, SLA targets and billing together. Preview a white-label workspace, then create your own tenant with a prepaid subscription.</p>
<div class="actions"><a class="cta primary" href="#demo">Explore the sample demo ↓</a><a class="cta" href="/hire?service=managed-ops-psa#checkout">Create your tenant →</a></div>
<p class="scope">Available today: tenant-scoped PSA, branding and signed monitoring intake. This is a focused product, not full ConnectWise or N-able feature parity, staffed support, EDR or unattended patch deployment.</p>
<div class="tiles">
<article><h3>01 · Explore</h3><p>Walk through sample fleet health, service tickets, patch/backup evidence and approval queues below. Demo data never enters your organization.</p></article>
<article><h3>02 · Subscribe</h3><p>Choose a plan and device allowance, enter your organization and authorized domain, then pay the generated Base-USDC invoice. No manually typed price or service code.</p></article>
<article><h3>03 · Make it yours</h3><p>Verified payment activates a separate tenant. Sign in with your private workspace credentials, apply your branding and enroll only authorized endpoints.</p></article>
</div>
<h2 id="integrations">Connect the tools you already operate.</h2>
<p class="scope">Each connection needs its own authorized scope. A listed integration is not automatically connected to any customer's account.</p>
<div class="tiles">
<article><span class="status">Read-only adapter available · setup required</span><h3>ScreenConnect</h3><p>Import access-session inventory from your separately licensed ScreenConnect instance. Pin the origin and session filter; credentials remain behind the connector.</p><a href="/ops/screenconnect">Configure ScreenConnect →</a><p class="scope">No remote-control session or unattended command execution is launched by this integration. Live instance validation is required.</p></article>
<article><span class="status">Planned · not available for activation</span><h3>Microsoft 365 &amp; Intune</h3><p>Planned read-only user, license, service-health and device evidence. Requires a tenant-specific application, least-privilege admin consent and connector validation.</p><p class="scope">No M365 monitoring, hardening or automated remediation is included until this connector is implemented and tested.</p></article>
<article><span class="status">Planned · not available for activation</span><h3>Google Workspace</h3><p>Planned directory and operational evidence for authorized Workspace domains. Administrative consent and scoped access must be established per customer.</p><p class="scope">Not currently connected. Do not enter a Google password or service-account key into a task brief.</p></article>
</div>
<h2 id="plans">A tenant of your own. Clear monthly pricing.</h2>
<div class="tiles plans">${selected.map(plan => `<article><h3>${plan.name}</h3><div class="plan-price">${money(plan.monthly_min_atomic)} USDC / month</div><p>${Number(plan.endpoint_monthly_atomic) ? `Plus ${money(plan.endpoint_monthly_atomic)} USDC per enrolled-device allowance per month.` : "No per-device charge for the PSA-only workspace; monitoring is not included."}</p><a class="cta" href="/hire?service=managed-ops-psa&amp;plan=${plan.id}#checkout">Choose plan &amp; create tenant →</a></article>`).join("")}</div>
<details><summary>What separates one tenant from another?</summary><p>Distinct tenant IDs, access credentials and tenant-scoped records separate your tickets, assets, telemetry and branding. This is logical isolation in shared infrastructure, not a dedicated database or cloud account.</p></details>
<details><summary>How do subscriptions and renewals work?</summary><p>The invoice is calculated server-side from the selected plan and device limit. Activation follows verified payment. Renewal produces a new prepaid invoice; MAG never debits your wallet automatically. Unpaid subscriptions expire. Keep your private recovery credentials safe.</p></details>
<details><summary>Does the demo connect to real devices?</summary><p>No. Northstar IT below is a fictional preview. Production workspaces start with their own records and accept only enrolled, authorized evidence. Patch and backup status are evidence fields, not proof that MAG deployed a patch or ran a backup.</p></details>
</section>`;
}
export { managedProductIntro };
